# Change these first
owner: Saypi Studio
repo: saypi-status

sites:
  - name: Saypi-Blog
    url: https://saypi.blog
  - name: Saypi Docs
    url: https://docs.saypi.blog/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.saypi.blog
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Saypi Status
  introTitle: "Intro Title Here"
  introMessage: Intro Message Here
  navbar:
    - title: GitHub
      href: https://github.com/Hsoj-dev/saypi-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
